### ISSUE TITLE
multilingual vectors 

### ISSUE THREAD

**Issue by justalingwist** [digling/intelligibility#1]
The vectors I thought we could use for the project are here: https://github.com/commonsense/conceptnet-numberbatch

**Comment by LinguList** [comment]
Where are they there? What files? I did not find the concrete links there...

**Comment by LinguList** [comment]
I see, thanks, they use a shell script to download them. So we do that as well.

**Comment by justalingwist** [comment]
Sorry, I realised I copied the wrong link to the main page. Here is the download link: https://conceptnet.s3.amazonaws.com/downloads/2019/numberbatch/numberbatch-19.08.txt.gz

**Comment by LinguList** [comment]
Did you see that, @justalingwist? They provide a shell-script that downloads the data. Yes, the shell script downloads the data. So that is the first step in our workflow.

**Comment by LinguList** [comment]
Or you make a file that you call `Makefile` and there you type:

```
download:
        wget https://conceptnet.s3.amazonaws.com/downloads/2019/numberbatch/numberbatch-19.08.txt.gz
```

**Comment by LinguList** [comment]
This should also work on a Mac, typing 

```
make download
```

In terminal would hten download all data.

**Comment by LinguList** [comment]
Better is:

```
download:
        curl -o "raw/numberbatch-1908.txt" https://conceptnet.s3.amazonaws.com/downloads/2019/numberbatch/numberbatch-19.08.txt.gz
```
`curl` is often already installed on mac, you must add a folder `raw` in the folder.
