### ISSUE TITLE
Added folder data

### ISSUE THREAD

**Issue by justalingwist** [digling/intelligibility#2]
I added a folder "data" with my way of creating a dataset that combines the CELEX data and the numberbatch vectors for Dutch and German to feed into an LDL model that I will run in the Julia environment as JudiLing package. Requirements here are a list of word forms that represent the phonological forms (transcription or as graphemes) and the vectors as .rda file to represent semantics. The latter I usually create my processing the dataset in R and saving the vectors as .rda matrices. Please have a look at the data folder and tell me if there is any other way of dealing with the data that you would prefer.

**Comment by LinguList** [comment]
What format is RDA? It is textbased, right?

**Comment by justalingwist** [comment]
Yes, I think it is text based. It’s used to store R data structures like vectors, matrices and data frames

**Comment by LinguList** [comment]
Just read it is a binary format that stores R data. So it is not recommended to be used to share it anywhere.

**Comment by LinguList** [comment]
But could you not read data from CSV in R as well?

**Comment by LinguList** [comment]
Ah, in Julia, there is a CSV reader, right? So rather use CSV.

**Comment by LinguList** [comment]
https://csv.juliadata.org
